#read csv

In [1]:
import pandas as pd
csv_movies=pd.read_csv(r"D:\My Files\Downloads\imdb-top-1000.csv")

In [2]:
csv_movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539,93.0

In [3]:
csv_movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000,96.0

In [4]:
csv_movies.dtypes

Series_Title         str
Released_Year        str
Runtime            int64
Genre                str
IMDB_Rating      float64
Director             str
Star1                str
No_of_Votes        int64
Gross              int64
Metascore        float64
dtype: object

In [5]:
csv_movies.shape

(1000, 10)

In [6]:
#column selection
csv_movies["Series_Title"]

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3        The Godfather: Part II
4                  12 Angry Men
                 ...
995      Breakfast at Tiffany's
996                       Giant
997       From Here to Eternity
998                    Lifeboat
999                The 39 Steps
Name: Series_Title, Length: 1000, dtype: str

In [7]:
#movies
csv_movies[["Series_Title","IMDB_Rating"]]

                 Series_Title  IMDB_Rating
0    The Shawshank Redemption          9.3
1               The Godfather          9.2
2             The Dark Knight          9.0
3      The Godfather: Part II          9.0
4                12 Angry Men          9.0
..                        ...          ...
995    Breakfast at Tiffany's          7.6
996                     Giant          7.6
997     From Here to Eternity          7.6
998                  Lifeboat          7.6
999              The 39 Steps          7.6

[1000 rows x 2 columns]

In [8]:
csv_movies[["Series_Title","IMDB_Rating","No_of_Votes"]]

                 Series_Title  IMDB_Rating  No_of_Votes
0    The Shawshank Redemption          9.3      2343110
1               The Godfather          9.2      1620367
2             The Dark Knight          9.0      2303232
3      The Godfather: Part II          9.0      1129952
4                12 Angry Men          9.0       689845
..                        ...          ...          ...
995    Breakfast at Tiffany's          7.6       166544
996                     Giant          7.6        34075
997     From Here to Eternity          7.6        43374
998                  Lifeboat          7.6        26471
999              The 39 Steps          7.6        51853

[1000 rows x 3 columns]

# Filtering :

Which movies have rating > 8.5?

In [9]:
csv_movies[csv_movies["IMDB_Rating"]>8.5]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000,96.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905,94.0
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762,94.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195,74.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102,66.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750,92.0
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182,82.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000,90.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365,87.0
14,The Matrix,1999,136,Action,8.7,Lana Wachowski,Lilly Wachowski,1676426,171479930,73.0
15,Goodfellas,1990,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394,90.0
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067,82.0
17,One Flew Over the Cuckoo's Nest,1975,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000,83.0
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844,96.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648,NaN
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017,74.0
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397,79.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859,96.0
24,Saving Private Ryan,1998,169,Drama,8.6,Steven Spielberg,Tom Hanks,1235804,216540909,91.0
25,The Green Mile,1999,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374,61.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247,59.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643,65.0
28,The Silence of the Lambs,1991,118,Crime,8.6,Jonathan Demme,Jodie Foster,1270197,130742922,85.0
29,Star Wars,1977,121,Action,8.6,George Lucas,Mark Hamill,1231473,322740140,90.0
30,Seppuku,1962,133,Action,8.6,Masaki Kobayashi,Tatsuya Nakadai,42004,373978394,85.0
31,Shichinin no samurai,1954,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061,98.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199,89.0

#Released_Year> 2000 :

Release year ka data type str hai or direct str ko int se compare nhi kr sakte phle usko numeric me convert krege phir filtering krege.

In [10]:

print(csv_movies["Released_Year"].dtype)

str

In [11]:
csv_movies["Released_Year"] = pd.to_numeric(csv_movies["Released_Year"],errors="coerce")

#1. pd.to_numeric() ka use kisi column ki values ko numeric data type (integer ya float) me convert krne ke liye hota hai.

#2.errors="coerce" ka matlab: Jo values numbers mein convert nahi ho sakti, unhe NaN bana do.

NaN ka matlab hai Not a Number, yani yahan valid numerical value available nahi hai.

In [12]:
csv_movies[csv_movies["Released_Year"] > 2000]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905,94.0
8,Inception,2010.0,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001.0,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750,92.0
13,The Lord of the Rings: The Two Towers,2002.0,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365,87.0
...,...,...,...,...,...,...,...,...,...,...
947,Harry Potter and the Sorcerer's Stone,2001.0,152,Adventure,7.6,Chris Columbus,Daniel Radcliffe,658185,317575550,64.0
948,The Others,2001.0,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687,74.0
949,Blow,2001.0,124,Biography,7.6,Ted Demme,Johnny Depp,240714,52990775,52.0
950,Enemy at the Gates,2001.0,131,Drama,7.6,Jean-Jacques Annaud,Jude Law,243729,51401758,53.0
951,Minority Report,2002.0,145,Action,7.6,Steven Spielberg,Tom Cruise,508417,132072926,80.0

In [13]:
#csv_movies[csv_movies['Released_Year'] > "2000"]

Which movies have runtime > 180?

In [14]:
csv_movies[csv_movies["Runtime"]>180]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905,94.0
7,Schindler's List,1993.0,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818,94.0
25,The Green Mile,1999.0,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374,61.0
31,Shichinin no samurai,1954.0,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061,98.0
59,Avengers: Endgame,2019.0,181,Action,8.4,Anthony Russo,Joe Russo,809955,858373000,78.0
71,Once Upon a Time in America,1984.0,229,Crime,8.4,Sergio Leone,Robert De Niro,311365,5321508,NaN
116,Lawrence of Arabia,1962.0,228,Adventure,8.3,David Lean,Peter O'Toole,268085,44824144,100.0
139,Bhaag Milkha Bhaag,2013.0,186,Biography,8.2,Rakeysh Omprakash Mehra,Farhan Akhtar,61137,1626289,NaN
140,Gangs of Wasseypur,2012.0,321,Action,8.2,Anurag Kashyap,Manoj Bajpayee,82365,5257741,89.0
156,"Swades: We, the People",2004.0,210,Drama,8.2,Ashutosh Gowariker,Shah Rukh Khan,83005,1223240,NaN
177,Sholay,1975.0,204,Action,8.2,Ramesh Sippy,Sanjeev Kumar,51284,932069480,NaN
206,Kis Uykusu,2014.0,196,Drama,8.1,Nuri Bilge Ceylan,Haluk Bilginer,46547,165520,88.0
240,Dil Chahta Hai,2001.0,183,Comedy,8.1,Farhan Akhtar,Aamir Khan,66803,300000,NaN
247,Lagaan: Once Upon a Time in India,2001.0,224,Adventure,8.1,Ashutosh Gowariker,Aamir Khan,105036,70147,84.0
258,Dilwale Dulhania Le Jayenge,1995.0,189,Drama,8.1,Aditya Chopra,Shah Rukh Khan,63516,15121644,NaN
274,Fanny och Alexander,1982.0,188,Drama,8.1,Ingmar Bergman,Bertil Guve,57784,4971340,100.0
278,The Deer Hunter,1978.0,183,Drama,8.1,Michael Cimino,Robert De Niro,311361,48979328,86.0
281,Barry Lyndon,1975.0,185,Adventure,8.1,Stanley Kubrick,Ryan O'Neal,149843,36008144,89.0
290,Andrei Rublev,1966.0,205,Biography,8.1,Andrei Tarkovsky,Anatoliy Solonitsyn,46947,102021,NaN
300,Ben-Hur,1959.0,212,Adventure,8.1,William Wyler,Charlton Heston,219466,74700000,90.0
314,Gone with the Wind,1939.0,238,Drama,8.1,Victor Fleming,George Cukor,290074,198676459,97.0
374,Kal Ho Naa Ho,2003.0,186,Comedy,8.0,Nikkhil Advani,Preity Zinta,63460,1787378,54.0
383,Magnolia,1999.0,188,Drama,8.0,Paul Thomas Anderson,Tom Cruise,289742,22455976,77.0
400,JFK,1991.0,189,Drama,8.0,Oliver Stone,Kevin Costner,142110,70405498,72.0
402,Dances with Wolves,1990.0,181,Adventure,8.0,Kevin Costner,Kevin Costner,240266,184208848,72.0
411,Gandhi,1982.0,191,Biography,8.0,Richard Attenborough,Ben Kingsley,217664,52767889,79.0
422,Fiddler on the Roof,1971.0,181,Drama,8.0,Norman Jewison,Topol,39491,80500000,67.0
430,Doctor Zhivago,1965.0,197,Drama,8.0,David Lean,Omar Sharif,69903,111722000,69.0
484,The Irishman,2019.0,209,Biography,7.9,Martin Scorsese,Robert De Niro,324720,7000000,94.0
549,Spartacus,1960.0,197,Adventure,7.9,Stanley Kubrick,Kirk Douglas,124339,30000000,87.0
552,The Ten Commandments,1956.0,220,Adventure,7.9,Cecil B. DeMille,Charlton Heston,63560,93740000,NaN
579,M.S. Dhoni: The Untold Story,2016.0,184,Biography,7.8,Neeraj Pandey,Sushant Singh Rajput,40416,1782795,NaN
629,Veer-Zaara,2004.0,192,Drama,7.8,Yash Chopra,Shah Rukh Khan,49050,2921738,67.0
652,Titanic,1997.0,194,Drama,7.8,James Cameron,Leonardo DiCaprio,1046089,659325379,75.0
686,The Right Stuff,1983.0,193,Adventure,7.8,Philip Kaufman,Sam Shepard,56235,21500000,91.0
812,Hamlet,1996.0,242,Drama,7.7,Kenneth Branagh,Kenneth Branagh,35991,4414535,NaN
817,Short Cuts,1993.0,188,Comedy,7.7,Robert Altman,Andie MacDowell,42275,6110979,79.0
820,Malcolm X,1992.0,202,Biography,7.7,Spike Lee,Denzel Washington,85819,48169908,73.0
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415,84.0

In [15]:
csv_movies[(csv_movies["IMDB_Rating"]>8.5) & (csv_movies["Runtime"]>150) ]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411,100.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905,94.0
6,Pulp Fiction,1994.0,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762,94.0
7,Schindler's List,1993.0,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818,94.0
10,The Lord of the Rings: The Fellowship of the Ring,2001.0,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750,92.0
12,"Il buono, il brutto, il cattivo",1966.0,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000,90.0
13,The Lord of the Rings: The Two Towers,2002.0,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365,87.0
18,Hamilton,2020.0,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783,90.0
20,Soorarai Pottru,2020.0,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648,NaN
21,Interstellar,2014.0,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017,74.0
24,Saving Private Ryan,1998.0,169,Drama,8.6,Steven Spielberg,Tom Hanks,1235804,216540909,91.0
25,The Green Mile,1999.0,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374,61.0
31,Shichinin no samurai,1954.0,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061,98.0

In [16]:
csv_movies.groupby("Genre")["IMDB_Rating"].mean()

Genre
Action       7.949419
Adventure    7.937500
Animation    7.930488
Biography    7.938636
Comedy       7.901290
Crime        8.016822
Drama        7.957439
Family       7.800000
Fantasy      8.000000
Film-Noir    7.966667
Horror       7.909091
Mystery      7.975000
Thriller     7.800000
Western      8.350000
Name: IMDB_Rating, dtype: float64

In [17]:
csv_movies.groupby("Genre")["Runtime"].mean()

Genre
Action       129.046512
Adventure    134.111111
Animation     99.585366
Biography    136.022727
Comedy       112.129032
Crime        126.392523
Drama        124.737024
Family       107.500000
Fantasy       85.000000
Film-Noir    104.000000
Horror       102.090909
Mystery      119.083333
Thriller     108.000000
Western      148.250000
Name: Runtime, dtype: float64

In [18]:
csv_movies.groupby("Genre")["No_of_Votes"].sum()

Genre
Action       72282412
Adventure    22576163
Animation    21978630
Biography    24006844
Comedy       27620327
Crime        33533615
Drama        61367304
Family         551221
Fantasy        146222
Film-Noir      367215
Horror        3742556
Mystery       4203004
Thriller        27733
Western       1289665
Name: No_of_Votes, dtype: int64

In [19]:
csv_movies.groupby("Genre")["IMDB_Rating"].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

genre wise avg rating chahiye , max rating , min rating , avg runtime uska ek report.

In [20]:
csv_movies.groupby("Genre").agg(Avg_Rating=("IMDB_Rating","mean"),Max_Rating=(("IMDB_Rating","max")),Min_Rating=(("IMDB_Rating","min")),Avg_Runtime=("Runtime","mean"))

           Avg_Rating  Max_Rating  Min_Rating  Avg_Runtime
Genre
Action       7.949419         9.0         7.6   129.046512
Adventure    7.937500         8.6         7.6   134.111111
Animation    7.930488         8.6         7.6    99.585366
Biography    7.938636         8.9         7.6   136.022727
Comedy       7.901290         8.6         7.6   112.129032
Crime        8.016822         9.2         7.6   126.392523
Drama        7.957439         9.3         7.6   124.737024
Family       7.800000         7.8         7.8   107.500000
Fantasy      8.000000         8.1         7.9    85.000000
Film-Noir    7.966667         8.1         7.8   104.000000
Horror       7.909091         8.5         7.6   102.090909
Mystery      7.975000         8.4         7.6   119.083333
Thriller     7.800000         7.8         7.8   108.000000
Western      8.350000         8.8         7.8   148.250000

In [21]:
csv_movies["Genre"].value_counts().head()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Name: count, dtype: int64

Find the top 10 highest-rated movies.

In [22]:
csv_movies.sort_values("IMDB_Rating",ascending=False).head(10)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469,80.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411,100.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000,96.0
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905,94.0
6,Pulp Fiction,1994.0,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762,94.0
7,Schindler's List,1993.0,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818,94.0
8,Inception,2010.0,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195,74.0
9,Fight Club,1999.0,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102,66.0

Which genre has the most movies?

In [23]:
csv_movies["Genre"].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [24]:
csv_movies["Director"].value_counts()

Director
Alfred Hitchcock       14
Steven Spielberg       13
Hayao Miyazaki         11
Martin Scorsese        10
Akira Kurosawa         10
                       ..
Martin Rosen            1
Wolfgang Reitherman     1
Richard Lester          1
Blake Edwards           1
George Stevens          1
Name: count, Length: 548, dtype: int64

**************************************************************************

Which genre has the most movies?

In [25]:
csv_movies["Genre"].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

Which genre has the highest average IMDb rating?

In [26]:
csv_movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

Which genre has the longest average runtime?

In [27]:
csv_movies.groupby("Genre")["Runtime"].mean().sort_values(ascending=False).head(1)

Genre
Western    148.25
Name: Runtime, dtype: float64

Which movie has the highest rating?

In [28]:
csv_movies.loc[csv_movies["IMDB_Rating"].idxmax(),["Series_Title","No_of_Votes"]]

Series_Title    The Shawshank Redemption
No_of_Votes                      2343110
Name: 0, dtype: object

Which movie has the highest number of votes?

In [29]:
csv_movies.loc[csv_movies["No_of_Votes"].idxmax(),["Series_Title","No_of_Votes"]]

Series_Title    The Shawshank Redemption
No_of_Votes                      2343110
Name: 0, dtype: object

Which movies have rating > 8.5?

In [30]:
csv_movies[csv_movies["IMDB_Rating"]>8.5]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469,80.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411,100.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000,96.0
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905,94.0
6,Pulp Fiction,1994.0,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762,94.0
7,Schindler's List,1993.0,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818,94.0
8,Inception,2010.0,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195,74.0
9,Fight Club,1999.0,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102,66.0
10,The Lord of the Rings: The Fellowship of the Ring,2001.0,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750,92.0
11,Forrest Gump,1994.0,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182,82.0
12,"Il buono, il brutto, il cattivo",1966.0,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000,90.0
13,The Lord of the Rings: The Two Towers,2002.0,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365,87.0
14,The Matrix,1999.0,136,Action,8.7,Lana Wachowski,Lilly Wachowski,1676426,171479930,73.0
15,Goodfellas,1990.0,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394,90.0
16,Star Wars: Episode V - The Empire Strikes Back,1980.0,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067,82.0
17,One Flew Over the Cuckoo's Nest,1975.0,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000,83.0
18,Hamilton,2020.0,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783,90.0
19,Gisaengchung,2019.0,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844,96.0
20,Soorarai Pottru,2020.0,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648,NaN
21,Interstellar,2014.0,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017,74.0
22,Cidade de Deus,2002.0,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397,79.0
23,Sen to Chihiro no kamikakushi,2001.0,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859,96.0
24,Saving Private Ryan,1998.0,169,Drama,8.6,Steven Spielberg,Tom Hanks,1235804,216540909,91.0
25,The Green Mile,1999.0,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374,61.0
26,La vita è bella,1997.0,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247,59.0
27,Se7en,1995.0,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643,65.0
28,The Silence of the Lambs,1991.0,118,Crime,8.6,Jonathan Demme,Jodie Foster,1270197,130742922,85.0
29,Star Wars,1977.0,121,Action,8.6,George Lucas,Mark Hamill,1231473,322740140,90.0
30,Seppuku,1962.0,133,Action,8.6,Masaki Kobayashi,Tatsuya Nakadai,42004,373978394,85.0
31,Shichinin no samurai,1954.0,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061,98.0
32,It's a Wonderful Life,1946.0,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199,89.0

Which movies have runtime > 180?

In [31]:
csv_movies[csv_movies["Runtime"]>180]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905,94.0
7,Schindler's List,1993.0,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818,94.0
25,The Green Mile,1999.0,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374,61.0
31,Shichinin no samurai,1954.0,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061,98.0
59,Avengers: Endgame,2019.0,181,Action,8.4,Anthony Russo,Joe Russo,809955,858373000,78.0
71,Once Upon a Time in America,1984.0,229,Crime,8.4,Sergio Leone,Robert De Niro,311365,5321508,NaN
116,Lawrence of Arabia,1962.0,228,Adventure,8.3,David Lean,Peter O'Toole,268085,44824144,100.0
139,Bhaag Milkha Bhaag,2013.0,186,Biography,8.2,Rakeysh Omprakash Mehra,Farhan Akhtar,61137,1626289,NaN
140,Gangs of Wasseypur,2012.0,321,Action,8.2,Anurag Kashyap,Manoj Bajpayee,82365,5257741,89.0
156,"Swades: We, the People",2004.0,210,Drama,8.2,Ashutosh Gowariker,Shah Rukh Khan,83005,1223240,NaN
177,Sholay,1975.0,204,Action,8.2,Ramesh Sippy,Sanjeev Kumar,51284,932069480,NaN
206,Kis Uykusu,2014.0,196,Drama,8.1,Nuri Bilge Ceylan,Haluk Bilginer,46547,165520,88.0
240,Dil Chahta Hai,2001.0,183,Comedy,8.1,Farhan Akhtar,Aamir Khan,66803,300000,NaN
247,Lagaan: Once Upon a Time in India,2001.0,224,Adventure,8.1,Ashutosh Gowariker,Aamir Khan,105036,70147,84.0
258,Dilwale Dulhania Le Jayenge,1995.0,189,Drama,8.1,Aditya Chopra,Shah Rukh Khan,63516,15121644,NaN
274,Fanny och Alexander,1982.0,188,Drama,8.1,Ingmar Bergman,Bertil Guve,57784,4971340,100.0
278,The Deer Hunter,1978.0,183,Drama,8.1,Michael Cimino,Robert De Niro,311361,48979328,86.0
281,Barry Lyndon,1975.0,185,Adventure,8.1,Stanley Kubrick,Ryan O'Neal,149843,36008144,89.0
290,Andrei Rublev,1966.0,205,Biography,8.1,Andrei Tarkovsky,Anatoliy Solonitsyn,46947,102021,NaN
300,Ben-Hur,1959.0,212,Adventure,8.1,William Wyler,Charlton Heston,219466,74700000,90.0
314,Gone with the Wind,1939.0,238,Drama,8.1,Victor Fleming,George Cukor,290074,198676459,97.0
374,Kal Ho Naa Ho,2003.0,186,Comedy,8.0,Nikkhil Advani,Preity Zinta,63460,1787378,54.0
383,Magnolia,1999.0,188,Drama,8.0,Paul Thomas Anderson,Tom Cruise,289742,22455976,77.0
400,JFK,1991.0,189,Drama,8.0,Oliver Stone,Kevin Costner,142110,70405498,72.0
402,Dances with Wolves,1990.0,181,Adventure,8.0,Kevin Costner,Kevin Costner,240266,184208848,72.0
411,Gandhi,1982.0,191,Biography,8.0,Richard Attenborough,Ben Kingsley,217664,52767889,79.0
422,Fiddler on the Roof,1971.0,181,Drama,8.0,Norman Jewison,Topol,39491,80500000,67.0
430,Doctor Zhivago,1965.0,197,Drama,8.0,David Lean,Omar Sharif,69903,111722000,69.0
484,The Irishman,2019.0,209,Biography,7.9,Martin Scorsese,Robert De Niro,324720,7000000,94.0
549,Spartacus,1960.0,197,Adventure,7.9,Stanley Kubrick,Kirk Douglas,124339,30000000,87.0
552,The Ten Commandments,1956.0,220,Adventure,7.9,Cecil B. DeMille,Charlton Heston,63560,93740000,NaN
579,M.S. Dhoni: The Untold Story,2016.0,184,Biography,7.8,Neeraj Pandey,Sushant Singh Rajput,40416,1782795,NaN
629,Veer-Zaara,2004.0,192,Drama,7.8,Yash Chopra,Shah Rukh Khan,49050,2921738,67.0
652,Titanic,1997.0,194,Drama,7.8,James Cameron,Leonardo DiCaprio,1046089,659325379,75.0
686,The Right Stuff,1983.0,193,Adventure,7.8,Philip Kaufman,Sam Shepard,56235,21500000,91.0
812,Hamlet,1996.0,242,Drama,7.7,Kenneth Branagh,Kenneth Branagh,35991,4414535,NaN
817,Short Cuts,1993.0,188,Comedy,7.7,Robert Altman,Andie MacDowell,42275,6110979,79.0
820,Malcolm X,1992.0,202,Biography,7.7,Spike Lee,Denzel Washington,85819,48169908,73.0
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415,84.0

Which genre has the highest total votes?

In [32]:
csv_movies.groupby("Genre")["No_of_Votes"].sum().sort_values(ascending=False).head(1)

Genre
Action    72282412
Name: No_of_Votes, dtype: int64

Genre-wise average rating and average runtime?

In [33]:
csv_movies.groupby("Genre").agg({"IMDB_Rating":"mean","Runtime":"mean"})

           IMDB_Rating     Runtime
Genre
Action        7.949419  129.046512
Adventure     7.937500  134.111111
Animation     7.930488   99.585366
Biography     7.938636  136.022727
Comedy        7.901290  112.129032
Crime         8.016822  126.392523
Drama         7.957439  124.737024
Family        7.800000  107.500000
Fantasy       8.000000   85.000000
Film-Noir     7.966667  104.000000
Horror        7.909091  102.090909
Mystery       7.975000  119.083333
Thriller      7.800000  108.000000
Western       8.350000  148.250000

Find the top 10 highest-rated movies.

In [34]:
csv_movies.sort_values("IMDB_Rating",ascending=False).head(10)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469,80.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411,100.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000,96.0
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905,94.0
6,Pulp Fiction,1994.0,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762,94.0
7,Schindler's List,1993.0,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818,94.0
8,Inception,2010.0,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195,74.0
9,Fight Club,1999.0,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102,66.0

* Aggregation/agg() : ka use data ko summarize krne ke liye hota hai. Iski help se hum ek ya multiple columns par average, total, maximum, minimum aur count jaise calculations kar sakte hain.

* Ek column par aggregation : df["Rating"].agg("mean")

* groupby() ke saath agg() ka use :

df.groupby("Genre").agg({
    "Rating": "mean",
    "Runtime": "mean"
})

* Ek column par multiple aggregations :

df.groupby("Genre").agg({
    "Rating": ["mean", "max", "min"]
})

In [41]:
csv_movies.shape

(1000, 10)

In [50]:
# Table 1: Movie aur Genre
movies = csv_movies[["Series_Title", "Genre"]].copy()

# Table 2: Movie aur Rating
ratings = csv_movies[["Series_Title", "IMDB_Rating"]].copy()

# Movie name ko index banayein
movies = movies.set_index("Series_Title")
ratings = ratings.set_index("Series_Title")

# Dono tables join karein
result = movies.join(ratings)

print(result.head())

                           Genre  IMDB_Rating
Series_Title
The Shawshank Redemption   Drama          9.3
The Godfather              Crime          9.2
The Dark Knight           Action          9.0
The Godfather: Part II     Crime          9.0
12 Angry Men               Crime          9.0

In [52]:
#Left join
result=movies.join(ratings,how='left')
print(result)

                           Genre  IMDB_Rating
Series_Title
The Shawshank Redemption   Drama          9.3
The Godfather              Crime          9.2
The Dark Knight           Action          9.0
The Godfather: Part II     Crime          9.0
12 Angry Men               Crime          9.0
...                          ...          ...
Breakfast at Tiffany's    Comedy          7.6
Giant                      Drama          7.6
From Here to Eternity      Drama          7.6
Lifeboat                   Drama          7.6
The 39 Steps               Crime          7.6

[1002 rows x 2 columns]

In [53]:

# Table 1: Movie details
movies = pd.DataFrame({
    "Genre": ["Drama", "Action", "Comedy", "Thriller"],
    "Year": [2016, 2023, 2009, 2022]
}, index=["Dangal", "Jawan", "3 Idiots", "Drishyam"])

# Table 2: Movie ratings
ratings = pd.DataFrame({
    "Rating": [8.4, 7.0, 8.4, 8.2],
    "Votes": [2000, 1500, 1800, 1200]
}, index=["Dangal", "Jawan", "PK", "Drishyam"])

print("MOVIES TABLE")
print(movies)

print("\nRATINGS TABLE")
print(ratings)

MOVIES TABLE
             Genre  Year
Dangal       Drama  2016
Jawan       Action  2023
3 Idiots    Comedy  2009
Drishyam  Thriller  2022

RATINGS TABLE
          Rating  Votes
Dangal       8.4   2000
Jawan        7.0   1500
PK           8.4   1800
Drishyam     8.2   1200

In [54]:

# Report A: Movie details
movies = pd.DataFrame({
    "Genre": ["Drama", "Action", "Comedy", "Thriller"],
    "Year": [2016, 2023, 2009, 2022]
}, index=["Dangal", "Jawan", "3 Idiots", "Drishyam"])

# Report B: Rating information available
ratings = pd.DataFrame({
    "Rating": [8.4, 7.0, 8.2, 7.8],
    "Votes": [2000, 1500, 1200, 900]
}, index=["Dangal", "Jawan", "Drishyam", "Pathaan"])

print("MOVIE DETAILS")
print(movies)

print("\nRATING DETAILS")
print(ratings)

MOVIE DETAILS
             Genre  Year
Dangal       Drama  2016
Jawan       Action  2023
3 Idiots    Comedy  2009
Drishyam  Thriller  2022

RATING DETAILS
          Rating  Votes
Dangal       8.4   2000
Jawan        7.0   1500
Drishyam     8.2   1200
Pathaan      7.8    900

In [55]:
result = movies.join(ratings, how="left")
print(result)

             Genre  Year  Rating   Votes
Dangal       Drama  2016     8.4  2000.0
Jawan       Action  2023     7.0  1500.0
3 Idiots    Comedy  2009     NaN     NaN
Drishyam  Thriller  2022     8.2  1200.0